### ISSUE TITLE
"error:  Unexpected token :" on Windows 10 / node v5.6.0

### ISSUE THREAD

**Issue by BigBlueHat** [jessedc/ajv-cli#11]
Sadly, it gives me no more than this:
```
$ ajv validate -s minimal.jsonschema -d minimal.json
error:  Unexpected token :
```

This is running via bash in Windows 10 on node v5.6.0 and the latest ajv-cli.

**Comment by epoberezkin** [comment]
Looks like a JSON file error. Error reporting can be improved though.

**Comment by BigBlueHat** [comment]
I initially thought so too, but they're valid JSON (re: jsonlint.com) and valid schemas also (re: ajv via tonic):
https://tonicdev.com/571e686f0ec3e817006565a5/571e686f0ec3e817006565a6

So...I think it's in the code...somewherez. Trying to build and test on Windows and will report if/when I get more errors.

**Comment by BigBlueHat** [comment]
Got the tests running after doing the following:
* commented out line https://github.com/jessedc/ajv-cli/blob/master/.eslintrc.yml#L8 because Windows uses CRLF
* set `CLI_TEST_COVERAGE` via bash (`export CLI_TEST_COVERAGE=true`) and removed it from the `package.json` test command--otherwise it failed with this error:

> 'CLI_TEST_COVERAGE' is not recognized as an internal or external command,
operable program or batch file.

After which all the tests pass.

However, running `node test.js -s example.jsonschema -d example.json` (where files are from the above Tonic URL), the error is the same:
```
error:  Unexpected token :
```

**Comment by apeschel** [comment]
:+1: for this issue.

I managed to determine that this is caused when the schema file ends in any extension other than `.json`.  In your example, `.jsonschema` is causing the problem. No idea what this maps to in the code though.

**Comment by epoberezkin** [comment]
I see. It loads the files using require that probably can't correctly parse files in this case... The motivation for this is to support js files as well (where comments are allowed etc.). Probably should be improved that if the extension is not json and not js, it can just load and parse file
