### ISSUE TITLE
Self referencing schemas are not compile-able 

### ISSUE THREAD

**Issue by morsh** [jessedc/ajv-cli#21]
Hi,
My schema looks something like this: (look below - specifically at **steps**)
It has two references to itself but I can't seem to be able to compile the schema (or run a validation process of a json against it). I also tried adding --v5 with no avail.

Is this fixable?

```json
{
  "type": "object",
  "id": "dialog",
  "properties": {
    "steps": { "$ref": "#/definitions/steps" },
    }
  },
  "definitions": {
    "steps": {
      "id": "steps",
      "type": "array",
      "items": {
        "type": "object",
        "oneOf": [
          {
            "id": "step",
            "properties": {
              "scenarios": {
                "type": "array",
                "items": {
                  "type": "object",
                  "properties": {
                    "steps": {
                      "$ref": "#/definitions/steps"
                    }
                  }
                }
              }
            }
          },
          { ... }
        ]
     }
  }
}
```

**Comment by epoberezkin** [comment]
@morsh Does this issue happen if you use Ajv from code? If so please submit the issue there. Or please add the information required in new issue template: https://github.com/epoberezkin/ajv/issues/new

If you are trying to compile with -o option to generate a standalone module then it may be not supported for this schema (see [limitations](https://github.com/epoberezkin/ajv-pack#limitations)) - you would need to use Ajv from code.

**Comment by morsh** [comment]
hi @epoberezkin 
I opened another issue tailing the problem emitted via code:
https://github.com/epoberezkin/ajv/issues/329

**Comment by epoberezkin** [comment]
resolved in https://github.com/epoberezkin/ajv/issues/329
