### ISSUE TITLE
Validate against draft-04?

### ISSUE THREAD

**Issue by clenk** [jessedc/ajv-cli#28]
[ajv lets you load the draft-04 meta-schema](https://github.com/epoberezkin/ajv/releases/tag/5.0.1-beta.0). Is there a way to do this in the cli? If I try to add it using `-m` it can't find it because it's trying to find the schema on my local filesystem.

```bash
$ ajv compile -s "schemas/myschema.json" -m "http://json-schema.org/draft-04/schema#"
$ error:  Cannot find meta-schema '/home/****/projects/my-schemas/http:/json-schema.org/draft-04/schema#'
```

**Comment by epoberezkin** [comment]
cli doesn't support remote meta-schemas/schemas, they should be in files.
That can be an additional feature here maybe.
There is draft-04 meta schema available inside node_modules/ajv - see migration guide for Ajv 5.0.0.

**Comment by handrews** [comment]
@epoberezkin It seems like the draft-06 meta-schema is recognized automatically but draft-04 is not and has to be passed as a local file.  Is there a particular reason for the distinction?  Also I'm pretty sure that before I updated recently it would happily recognize draft-04 without having to be passed a file.

**Comment by epoberezkin** [comment]
@handews no reason really, just need to add it. I will do it today.

**Comment by epoberezkin** [comment]
you still can migrate draft-04 schemas even without this change because it uses json-schema-migrate that has a separate Ajv instance that includes draft-04, draft-04-hyper and v5 meta-schemas already.

**Comment by epoberezkin** [comment]
in 2.1.0
