### ISSUE TITLE
Update to Version 0.2

### ISSUE THREAD

**Issue by jessedc** [jessedc/ajv-cli#3]
Since merging #2, update the published version on npm. 

https://docs.npmjs.com/getting-started/publishing-npm-packages#updating-the-package

**Comment by ami44** [comment]
have you a date to publish on npm version 0.2 ?

**Comment by epoberezkin** [comment]
+1

**Comment by epoberezkin** [comment]
I need some further improvements but the last update wasn't published to npm... What's the plan?
