### ISSUE TITLE
Question: referencing definition imported with -r option from another file

### ISSUE THREAD

**Issue by GiovanniFrigo** [jessedc/ajv-cli#30]
Opening a new issue to avoid spamming #29. May be a pretty n00bish question :)

From what I read from the documentation I should be able to load schemas with the `-r` option, and the expected behaviour is that "The schema in -s parameter can reference any of these schemas with $ref keyword.". 
However, I'm not currently able to correctly reference the schema in the file.

I'm running the cli like this: `ajv validate -r schemas/definitions.json -s schemas/devices-schema.json -d devices/devices.json`, where `schemas/definitions.json` contains only one definition:

```
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "id": "http://belka.us/schemas/definitions.json",
  "definitions": {
    "address": {
      "type": "string",
      "description": "An hardware address in hexadecimal format",
      "pattern": "^0x[0-9A-F]{4}$"
    }
  }
}
```

I would then like to use that definition in `devices-schema.json`, but I'm failing in finding the correct syntax to do so.

```
"properties": {
        "version":        { "$ref": "/definitions.json/definitions/address" },
```

**Comment by epoberezkin** [comment]
Provided that devices-schema.json has "id" attribute "http://belka.us/schemas/devices-schema.json" (i.e. in the same host and path as definitions.json), the $ref should be "definitions.json#/definitions/address".

File names are not used, schemas should be referred to by their IDs, according to the spec.

**Comment by GiovanniFrigo** [comment]
Thanks, it works like a charm! I was trying to use the whole ID instead of only the filename of the ID.

BTW, I'm loving this package, keep up the good work!

**Comment by epoberezkin** [comment]
using the whole ID would work too, as long as JSON path is in hash fragment.
