### ISSUE TITLE
Provide directory watcher flag to run validation when files change

### ISSUE THREAD

**Issue by alanwsmith** [jessedc/ajv-cli#40]
Feature Request:

Create a flag (e.g. `--watch`) that watches the target files for changes and re-runs the validation automatically when they occur.

The idea being to have a separate window open and running that shows immediate validation results ever time a change to the schema or data files is detected.

**Comment by epoberezkin** [comment]
[watch cli](https://www.npmjs.com/package/watch#cli) can do it, as well as many other utilities. This should not be a feature of this package.
