### ISSUE TITLE
Beta Build Linked to ajv@beta?

### ISSUE THREAD

**Issue by jthomerson** [jessedc/ajv-cli#44]
Could a next-version beta build be released that uses `ajv@beta`? I want to use draft 07, but that requires `ajv@beta`.

**Comment by epoberezkin** [comment]
Ajv 6.0.0 is released, so the new major version should be released for ajv-cli as well.

**Comment by epoberezkin** [comment]
in https://github.com/jessedc/ajv-cli/releases/tag/v3.0.0
