### ISSUE TITLE
Can't $ref relative file.

### ISSUE THREAD

**Issue by HoraceShmorace** [jessedc/ajv-cli#46]
I'm having trouble using a parent schema that references a child schema via a relative URL.

Here's my parent schema:
```
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "id": "parent.json",
  "description": "The parent schema.",
  "type": "object",
  "properties": {
    "parentProp1": { "type": "string"},
    "parentProp2": { "$ref": "child.json#"}
  }
}
```

Here's my child schema:
```
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "description": "The parent schema.",
  "type": "object",
  "properties": {
    "childProp1": { "type": "number" }
  }
}
```

Here's my data:
```
{
  "parentProp1": "one",
  "parentProp2": {
    "childProp1": 1
  }
}
```

Here's the error I get:

> $ ajv -s parent.json -d parent-test.json
> schema parent.json is invalid
> error: can't resolve reference child.json# from id parent.json#

**Comment by epoberezkin** [comment]
File location is irrelevant, only $id (or id) attribute in the schema file is used for $refs (that's per JSON schema spec) and you need to use -r option to make ajv-cli aware of the existence of the referenced file.
