### ISSUE TITLE
Does ajv-cli tool validates the format type of specification.

### ISSUE THREAD

**Issue by ShwetaManekari** [jessedc/ajv-cli#53]
Hello All,
Given below is the specification in which we have type and format of fields. I am able to validate the specification with type parameter with ajv-cli  but I also want to validate with **format** parameter. Is there a way to validate specification with format parameter?
"schema"{
"properties": {
        "startDate": {
          "type": "string",
          "format": "date"
        },        
        "storage": {
          "type": "number",
          "format": "float"
        }
}

**Comment by epoberezkin** [comment]
it supports the same as Ajv - so it does.
