### ISSUE TITLE
[Feature Request] Is it possible to convert JSON schema to protobuf file?

### ISSUE THREAD

**Issue by hiberabyss** [jessedc/ajv-cli#58]

**Comment by epoberezkin** [comment]
What is it? What is the use case?

**Comment by hiberabyss** [comment]
In some case, there is a service written with JS using JSON schema, while someday the service need to be rewritten with c++ and protobuf is preferred. 

In this case, it will be very useful to convert the JSON schema file into protobuf definition file.

Thanks!

**Comment by epoberezkin** [comment]
I think it is out of scope - it’s not JSON Schema specific. I believe there should be some other utility to serialise any JSON into protobuf.
