### ISSUE TITLE
ajv compile not failing if required properties are not defined

### ISSUE THREAD

**Issue by DavidBiesack** [jessedc/ajv-cli#64]
`ajv compile -s /tmp/ajv.json` does not fail where the required properties are not
defined in the schema and additionalProperties is false.

file /tmp/ajv.json:
```
{
  "$schema": "http://json-schema.org/draft-06/schema#",
  "id": "https://api.apiture.com/schemas/audit/authorizedSignerInvited/v1.0.0/schema.json",
  "type": "object",
  "description": "Sample schema with invalid \"required\" aray",
  "additionalProperties": false,
  "required": [
    "aa"
  ],
  "properties": {
    "a": {
      "description": "value a",
      "type": "string"
    },
    "aaa": {
      "description": "value aaa",
      "type": "string"
    }
  }
}
```

compile it:

$ ajv compile -s /tmp/ajv.json
schema /tmp/ajv.json is valid

I believe this should fail

**Comment by epoberezkin** [comment]
required keyword only requires that the property is present in the data, not that it is defined in the schema.
