### ISSUE TITLE
GitLab CI not possible when more than one JSON file for validation is found

### ISSUE THREAD

**Issue by sukhoi191** [jessedc/ajv-cli#65]
I've prepared a very simple GitLab repo to show this problem: https://gitlab.com/sukhoi191/ajv-cli-pipeline-test

Basically, when these criteria are met:
1. GitLab CI configuration has step similar to this one: `ajv -s __documentation__/json-schema/Blacklist.schema.json -d __data__/*Blacklist.json` (see: https://gitlab.com/sukhoi191/ajv-cli-pipeline-test/blob/master/.gitlab-ci.yml)
2. In `__data__` directory, there is more than one file that matches the wildcard (e.g. `SampleBlacklist.json` and `SampleAnotherBlacklist.json`, see: https://gitlab.com/sukhoi191/ajv-cli-pipeline-test/tree/master/__data__).

GitLab pipeline fails on executing ajv with message:

```
$ ajv -s __documentation__/json-schema/Blacklist.schema.json -d __data__/*Blacklist.json
Unknown command __data__/SampleBlacklist.json
```

Example: https://gitlab.com/sukhoi191/ajv-cli-pipeline-test/-/jobs/325663668

When I run this command locally on my computer, it works without any problems.

I'm not sure if this is more ajv-cli issue, or maybe GitLab one.

**Comment by epoberezkin** [comment]
GitLab probably processes the wildcard instead of passing it Ajv-cli. Try quoting the file pattern - maybe it will be passed as is.

**Comment by sukhoi191** [comment]
Thank you! It works when I put the file pattern in quotes: https://gitlab.com/sukhoi191/ajv-cli-pipeline-test/-/jobs/335526700
