### ISSUE TITLE
Run tests on travis

### ISSUE THREAD

**Issue by epoberezkin** [jessedc/ajv-cli#9]
@jessedc can you please enable the repo on [travis](https://travis-ci.org/profile/jessedc)? I've done the code, just need to push...

**Comment by jessedc** [comment]
I have enabled the project on travis

**Comment by epoberezkin** [comment]
Thanks! When you have a minute please also set CODECLIMATE_REPO_TOKEN environment variable in [Travis settings](https://travis-ci.org/jessedc/ajv-cli/settings). You can find it at https://codeclimate.com/github/jessedc/ajv-cli -> Settings -> Test Coverage -> Travis logo
